# Basic Info
title: 9ci Inc
email: connection@9ci.com
description: >
  9ci Receivables management and accounts receivable solutions to optimize your invoicing, collections, cash application and deductions management processes.
# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://www.9ci.com"
# comment_server_url: "https://squabble.9ci.com"
# comment_server_enabled: 1

# Professional and social media links
twitter_username: 9ci
github_username: 9ci

# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

# Include static pages.
include: ["_pages"]

# Blog
paginate: 9
paginate_path: "/articles/page-:num/"

# For Travis CI and gulp
exclude: ["_pages/results.html", "vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "hologram_config.yml"]

permalink: /articles/:title

# Collections
collections:
  team:
    output: true
    permalink: /company/:path/
  case-studies:
    output: true
    permalink: /results/case-studies/:path/
  services:
    output: true
    permalink: /services/:path/
  solutions:
    output: true
    permalink: /solutions/:path/

# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll-picture-tag
  - jemoji
# - jekyll-twitter-plugin

# Picture element presets
picture:
  source: "assets/img"
  output: "assets/processed-img"
  markup: "picture"
  presets:
    team_square:
      attr:
        class: "image--team-square"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "334"
      source_default:
        width: "254"
    team_individual:
      attr:
        class: "image--team-individual"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "350"
      source_default:
        width: "288"
    team_square_small:
      attr:
        class: "image--team-square-small"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "288"
    team_blog_tile:
      attr:
        class: "image--team-blog-tile"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "60"
    partner_square:
      attr:
        class: "image--partner-square"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "223"
    post_featured_image:
      attr:
        class: "image--post-featured-image"
        itemprop: "image"
      ppi: [1, 2]
      source_1120:
        media: "(min-width: 1120px)"
        width: "1000"
      source_860:
        media: "(min-width: 860px)"
        width: "746"
      source_640:
        media: "(min-width: 640px)"
        width: "860"
      source_400:
        media: "(min-width: 400px)"
        width: "640"
      source_default:
        width: "400"
        
# Add for default for og:image meta tag
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/logo.svg"
